### ISSUE TITLE
There is no python3.6 when using image radanalyticsio/openshift-spark-py36:2.4-latest

### ISSUE THREAD

**Issue by nmelche** [radanalyticsio/spark-operator#297]
There is no python version 3.6 when using the image radanalyticsio/openshift-spark-py36:2.4-latest
#### Steps to reproduce:

  1. Pull the image radanalyticsio/openshift-spark-py36:2.4-latest
  2. type in 'python' -> it shows python 2.7

Am I doing something wrong? I can't find a python 3.6 version :(

**Comment by elmiko** [comment]
hi,

these images are not meant to be run from an interactive command line. there are actually 2 python versions installed in the py36 images, this is due to the base image using a python2 binary by default. the python36 binary is accessible using the software collection library (scl), to use it you would need to first run `/opt/app-root/etc/scl_enable` and then the python command.

this image is based on centos/python-36-centos7, i would look inside that image if you are curious about how these python versions live together.
